### ISSUE TITLE
Got "could not find driver" when running "php artisan filament-icons:install"

### ISSUE THREAD

**Issue by capungindia** [tomatophp/filament-icons#1]
Hi, i'm new to filament and want to try using filament-cms. Trying to follow https://filamentphp.com/plugins/3x1io-tomato-cms step-by-step. Everything run well until i tried to add Categories when i get this error. 
![image](https://github.com/user-attachments/assets/ef61d65a-cef4-4631-8b75-5055fc05f3b9)
The strage thing is that this error supposed to appear when there is a problem with database connection, isn't it (cmiiw)? As far as i know, i have no problem accessing my database since i could do login.

I tried to follow https://filamentphp.com/plugins/3x1io-tomato-icons to get proper filament-icons installation buat then get the same error right here
![image](https://github.com/user-attachments/assets/701f0b98-29f3-436d-ac06-af03be7a8e77)

Is filament-icons have a specific database configuration separated from the one of laravel?

Thank you

**Comment by capungindia** [comment]
I've found it. It is turn out to be just me didn't notice that filament-icons based on Sushi that need pdo_sqlite to be enabled. Enabling it in php.ini and then everything work fine for me.

Thank you

**Comment by Dontorpedo** [comment]
after enabling pdo_sqlite i have the error:   SQLSTATE[HY000]: General error: 1 no such table: icons (Connection: , SQL: select * from "icons")

**Comment by capungindia** [comment]
@Dontorpedo try this
- run php artisan vendor:publish --tag=blade-icons
- in config/blade-icons.php uncomment default section
- run npm install heroicons
- create config/generations.php (example: https://github.com/blade-ui-kit/blade-heroicons/blob/main/config/generation.php)
- run .\vendor\bin\blade-icons-generate

**Comment by yagnesh987** [comment]
php artisan filament-icons:install

still the issue is there after following this commands NO TABLE or migration is there

**Comment by fadymondy** [comment]
hi, all it's very easy to make sure you have SQLite3 on your PHP .ini

**Comment by yagnesh987** [comment]
> hi, all it's very easy to make sure you have SQLite3 on your PHP .ini

I am using mysql I have raised an issue please check screenshots also.
