### ISSUE TITLE
php artisan filament-icons:install (

### ISSUE THREAD

**Issue by yagnesh987** [tomatophp/filament-icons#2]
Illuminate\Database\QueryException

SQLSTATE[HY000]: General error: 1 no such table: icons (Connection: , SQL: select * from "icons")
I cannot see database migration file to publish and copy from vendor folder and getting issues due to this icons table not found please check attached screenshot and revert me back after issue is being resolved.

![Screenshot from 2024-11-15 11-42-52](https://github.com/user-attachments/assets/0df750b9-c0ae-43b6-a1e9-509ce0ed6047)
![Screenshot from 2024-11-15 11-43-44](https://github.com/user-attachments/assets/8651d490-6594-45e7-a9c3-92c69eda454f)

**Comment by yagnesh987** [comment]
> [TOT-146 php artisan filament-icons:install (](https://linear.app/tomatophp/issue/TOT-146/php-artisan-filament-iconsinstall)

Not working

**Comment by helpinto81** [comment]
same here

**Comment by fadymondy** [comment]
your problem with the cache driver!

to fix this try publishing the config file 

```bash
php artisan vendor:publish --tag="filament-icons-config"
```

then on your config file 

```php
"cache" => false
```

**Comment by yagnesh987** [comment]
> your problem with the cache driver!
> 
> to fix this try publishing the config file
> 
> ```shell
> php artisan vendor:publish --tag="filament-icons-config"
> ```
> 
> then on your config file
> 
> ```
> "cache" => false
> ```

my concern is not publishing issue I cannot find migration file first of all fix that due to that I am facing issues in other cms packages!

**Comment by paul2Dev** [comment]
> your problem with the cache driver!
> 
> to fix this try publishing the config file
> 
> ```shell
> php artisan vendor:publish --tag="filament-icons-config"
> ```
> 
> then on your config file
> 
> ```
> "cache" => false
> ```

Hi @3x1io, i've published the "**filament-icons-config**" and set the **cache to false**, but i still get the error that it is trying to fetch the icons from database table, when i try to create a folder, and i've saw that the model Icon is using Sushi to map icons from disk. i don't know why i still get the error like it's trying to fetch it from database :/ 

**could not find driver (Connection: , SQL: create table "icons" ("id" integer primary key autoincrement not null, "label" varchar, "name" varchar, "provider" varchar, "template" varchar, "template_class" varchar))** 

Also i get the same error when i try to install the icons with: **php artisan filament-icons:install**

**Comment by abitme** [comment]
still no update here?
